/**
 * Copy compiled ABIs out of Hardhat's artifacts/ into
 * packages/shared/src/abis/ so backend + frontend can import them
 * via @ballast/shared without reaching into contracts/artifacts.
 *
 * Runs automatically as part of `pnpm --filter @ballast/contracts build`.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

// Only export what the backend / frontend consume. MockERC20 is test-only —
// runtime callers use viem's built-in erc20Abi for any ERC-20 interaction.
const CONTRACTS_TO_EXTRACT = ['AllocationDesk'] as const;

const outDir = join(__dirname, '..', '..', 'shared', 'src', 'abis');
mkdirSync(outDir, { recursive: true });

const indexLines: string[] = [
  '// Auto-generated by packages/contracts/scripts/extract-abis.ts',
  '// Do NOT edit by hand — re-run `pnpm contracts:build`.',
  '',
];

for (const name of CONTRACTS_TO_EXTRACT) {
  const artifactPath = join(
    __dirname,
    '..',
    'artifacts',
    'contracts',
    `${name}.sol`,
    `${name}.json`
  );
  const artifact = JSON.parse(readFileSync(artifactPath, 'utf-8'));
  const out = `// Auto-generated by packages/contracts/scripts/extract-abis.ts
// Do NOT edit by hand — re-run \`pnpm contracts:build\`.
export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  writeFileSync(join(outDir, `${name}.ts`), out);
  indexLines.push(`export * from './${name}';`);
}
writeFileSync(join(outDir, 'index.ts'), indexLines.join('\n') + '\n');

console.log(`✓ Extracted ABIs: ${CONTRACTS_TO_EXTRACT.join(', ')}`);
console.log(`  Output: packages/shared/src/abis/`);
